# Generated by Django 3.2.3 on 2021-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_alter_starsystem_galaxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='moon',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
